// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYj7SgfjO6oUUiGwKWb48cS_jL67PPrP0',
    appId: '1:734218388713:android:554d414c7bf844e0e25c78',
    messagingSenderId: '734218388713',
    projectId: 'unofficial-filman-client',
    storageBucket: 'unofficial-filman-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvdQ3AroxBX0uuwGevE_1-lJEd0c1LNs',
    appId: '1:734218388713:ios:cb31877c6327a698e25c78',
    messagingSenderId: '734218388713',
    projectId: 'unofficial-filman-client',
    storageBucket: 'unofficial-filman-client.firebasestorage.app',
    iosBundleId: 'io.github.majusss.filman',
  );
}
