name: Multiplatform Build and Release

on:
  push:
    branches:
      - main

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/unofficial-filman-android.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: unofficial-filman-android.apk
          path: build/app/outputs/flutter-apk/unofficial-filman-android.apk

  ios-build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: Get Dependencies
        run: flutter pub get

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign

      - name: Create IPA File
        run: |
          mkdir -p Payload
          mv  /Users/runner/work/unofficial-filman-flutter/unofficial-filman-flutter/build/ios/iphoneos/Runner.app Payload/
          zip -qq -r -9 unofficial-filman-ios.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v2
        with:
          name: unofficial-filman-ios.ipa
          path: unofficial-filman-ios.ipa

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [android-build, ios-build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: unofficial-filman-android.apk

      - name: Download IPA Artifact
        uses: actions/download-artifact@v2
        with:
          name: unofficial-filman-ios.ipa

      - name: Create Release
        run: |
          current_date=$(date +'%Y-%m-%d_%H-%M-%S')
          gh release create "$current_date.${{ github.run_number }}" \
            --title "Release $current_date.${{ github.run_number }}" \
            --notes "Commit: \`$(git log -1 --pretty=format:'%h - %s')\`<br/>*Auto release*"
            /home/runner/work/unofficial-filman-flutter/unofficial-filman-flutter/unofficial-filman-android.apk /home/runner/work/unofficial-filman-flutter/unofficial-filman-flutter/unofficial-filman-ios.ipa
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

